import { Dimension } from "./packs";

export const researchNotes: Record<Dimension, { construct: string; basis: string; source: string; level: "established construct" | "behavioural hypothesis" }> = {
  optimization: { construct: "Efficiency preference", basis: "A playful behavioural hypothesis. Everyday shortcut choices do not establish a stable personality trait.", source: "Funder, The Personality Puzzle — trait, situation, and behaviour.", level: "behavioural hypothesis" },
  uncertainty: { construct: "Tolerance for ambiguity", basis: "An established construct about how people respond to unclear or complex situations.", source: "Budner (1962), Intolerance of ambiguity as a personality variable.", level: "established construct" },
  conformity: { construct: "Social influence and independence", basis: "The questions explore when other people act as information versus instruction.", source: "Cialdini, Influence — social proof; Funder — personality in situations.", level: "behavioural hypothesis" },
  planning: { construct: "Conscientiousness-related organisation", basis: "Preparation and orderliness are commonly studied facets, but five choices are only a weak signal.", source: "Cervone & Pervin, Personality: Theory and Research.", level: "established construct" },
  control: { construct: "Perceived control", basis: "This explores preference for agency and visibility in everyday decisions.", source: "Cervone & Pervin, Personality: Theory and Research.", level: "established construct" },
  risk: { construct: "Risk preference and loss sensitivity", basis: "Risk appetite depends heavily on context, stakes, and framing.", source: "Kahneman, Thinking, Fast and Slow; prospect theory research.", level: "established construct" },
  social: { construct: "Interpersonal sensitivity", basis: "A playful read on attention to social cues—not a measure of empathy or social skill.", source: "Funder, The Personality Puzzle — personality judgment.", level: "behavioural hypothesis" },
  detail: { construct: "Conscientiousness-related order and detail attention", basis: "Everyday noticing can be a clue, but not a diagnostic measure.", source: "Cervone & Pervin, Personality: Theory and Research.", level: "established construct" },
  novelty: { construct: "Openness to experience", basis: "Curiosity and preference for novelty are related to a well-studied broad personality domain.", source: "Funder, The Personality Puzzle — trait approach.", level: "established construct" },
  rules: { construct: "Norm sensitivity and rule orientation", basis: "A behavioural hypothesis about when rules are treated as meaningful versus arbitrary.", source: "Cialdini, Influence; Funder, The Personality Puzzle.", level: "behavioural hypothesis" },
  decision: { construct: "Deliberative versus intuitive decision style", basis: "The prompts reflect decision pace; they do not label one style as better.", source: "Kahneman, Thinking, Fast and Slow.", level: "behavioural hypothesis" },
  conflict: { construct: "Everyday assertiveness", basis: "Conflict behaviour changes with relationship, power, and stakes, so this remains a playful hypothesis.", source: "Cervone & Pervin, Personality: Theory and Research.", level: "behavioural hypothesis" },
};
